const ApiError = require('../exceptions/api-error');


class UserController{


async getUsers(req,res,next){
try {
  
} catch (error) {
  next(error)
}
}
async getUserOne(req,res,next){
try {
  
} catch (error) {
  next(error)
}
}




}


module.exports= new UserController()